<?php 
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Shopliebe
 * @package   Shopliebe_PasswordStrength
 * @author    Marcel Mellor <info@shopliebe.de>
 * @copyright 2014 Mellor Schuhmacher GbR
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.shopliebe.de
 */
?>

<script>
    Validation.methods['validate-existing-password'] = Validation.get('validate-password');
    Validation.add('validate-password', '<?php echo $this->getValidationMessage(); ?>', function(v) {
        var pass=v.strip(); /*strip leading and trailing spaces*/
        <?php echo $this->getValidationScript();?>
        return true;
    });
    document.observe("dom:loaded", function() {
        $$('#login-form #pass').
            invoke('removeClassName', 'validate-password').
            invoke('addClassName', 'validate-existing-password');
    });
</script>